apache/pekko-grpc

- .github/workflows/build-test.yml
- .github/workflows/format.yml
- project/Common.scala
Similar to pekko core, replaces the sbt scalafmt check with a github actions one. Also removes the `scalafmtOnCompile` check because it is now unnecessary (and it also doesn't play well with IDE's).
> Add github workflow to check scala code is formatted

- .asf.yaml
This should properly remove branch protection (see https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-Branchprotection)
> Properly remove branch protection

- CONTRIBUTING.md
- README.md
- benchmark-java/project/build.properties
- build.sbt
- project/Common.scala
Baby step towards Pekko renaming
Updating the org id is going to be more troublesome. The build is complicated and changing it just in sbt leads to issues like https://github.com/apache/incubator-pekko-grpc/actions/runs/3595637094/jobs/6055368466
The maven and gradle CI builds were already failing in main branch
> update some akka refs in markdown files

- .github/workflows/build-test.yml
- benchmark-java/project/build.properties
* https://github.com/apache/incubator-pekko-grpc/actions/runs/4005034918/jobs/6874908317
* we don't have an API key for fossa - disable for time being
* https://github.com/apache/incubator-pekko-grpc/actions/runs/4005034918/jobs/6874907835
* seems to be this issue - https://github.com/sbt/sbt/issues/6745#issuecomment-1379380681
* downgrade sbt version to one where issue doesn't happen
> CI build issues

- build.sbt
- project/Common.scala
- project/MetaInfLicenseNoticeCopy.scala
This PR solves the bug that was revealed in https://github.com/apache/incubator-pekko-grpc/pull/37#issuecomment-1449888452. In that PR I forgot to remove the already existing code for copying over files into META-INF so we ended up copying `LICENSE`/`NOTICE` and `DISCLAIMER` files twice.
@jrudolph Do you think there is merit in downgrading the sbt-assembly plugin incase the upgrade did any change that we are not aware of? I don't think this should be an issue, sbt people are usually very strict in not adding additional changes in future versions.
> Remove duplicate META-INF license entry

- build.sbt
- docs/src/main/paradox/server/grpc-web.md
- plugin-tester-java/build.gradle
- plugin-tester-java/pom.xml
- plugin-tester-scala/build.gradle
- plugin-tester-scala/pom.xml
- project/Dependencies.scala
- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/WebHandler.scala
- runtime/src/main/scala/org/apache/pekko/grpc/scaladsl/WebHandler.scala
Now that a snapshot of pekko-http-cors has been released (see https://github.com/lomigmegard/akka-http-cors/issues/258#issuecomment-1454762806) this PR undoes the removal (see https://github.com/apache/incubator-pekko-grpc/pull/23/commits/c41a89c2435894d8cb85985b252bd239d7a666d9 and https://github.com/apache/incubator-pekko-grpc/pull/23)
Resolves: https://github.com/apache/incubator-pekko-grpc/issues/22
> Undo removal of pekko-http-cors

- plugin-tester-java/build.gradle
- plugin-tester-scala/build.gradle
- plugin-tester-scala/pom.xml
- project/Dependencies.scala
Updates latest pekko snapshot to bring in latest ccompat changes. Although pekko-grpc doesn't need it, its best to make sure that our pekko modules have this pekko version as lowest common denominator so we don't get potential dependency resolution issues.
> Update pekko snapshot

- .scala-steward.conf
- benchmark-java/build.sbt
- plugin-tester-java/build.gradle
- plugin-tester-scala/build.gradle
- project/Dependencies.scala
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/src/test/scala/org/apache/pekko/grpc/GrpcInteropSpec.scala
- sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
* in pekko core, we have 'testkit' libs and those still support scalatest 3.1 for historic reasons (3.2 needed for scala 3 though).
* grpc doesn't have such a 'testkit', so seems tidier to use scalatest 3.2 - especially since pekko-http may soon support scala3 allowing pekko-grpc to potentially support scala3
> standardise on scalatest 3.2.15

- maven-plugin/src/main/maven/plugin.xml
The mojos in the pekkp-grpc Maven plugin are both singleton instantiated, but do not modify any Class or instance state, so should be safe to use on multiple worker threads.
This removes a warning when Maven is run with multiple worker threads (e.g. `mvn -T 4`):
> 
> [WARNING] *****************************************************************
> [WARNING] * Your build is requesting parallel execution, but project      *
> [WARNING] * contains the following plugin(s) that have goals not marked   *
> [WARNING] * as @threadSafe to support parallel building.                  *
> [WARNING] * While this /may/ work fine, please look for plugin updates    *
> [WARNING] * and/or request plugins be made thread-safe.                   *
> [WARNING] * If reporting an issue, report it against the plugin …
> Mark Maven plugin mojos as threadsafe.

- benchmarks/src/main/scala/org/apache/pekko/grpc/BenchRunner.scala
- maven-plugin/src/main/scala/org/apache/pekko/grpc/maven/AbstractGenerateMojo.scala
- project/CopyrightHeader.scala
Unwraps single string interpolation i.e. `s"${something}"` into `s"$something"`. Make sure to do a rebase merge of this PR because I need to add its commit to `.git-blame-ignore-revs`
> Unwrap single string interpolation syntax

- build.sbt
- project/NoPublish.scala
Regarding the PR that disabled javadoc publishing which was merged in order to get publishling to work (see https://github.com/apache/incubator-pekko-grpc/pull/78) I noticed that Pekko core implements a basic `NoPublish` sbt plugin which not only sets `publish / skip := true` but also disables publishing (see https://github.com/apache/incubator-pekko/blob/main/project/Publish.scala#L41C1-L49).
In order to avoid potential publishing issues (and also just out of design, if we do not publish an sbt project there is no point in generating docs) I have just ported this solution to pekko-grpc. There is one nuance just for pekk-grpc, which is `publishLocal / skip := false` for `interopt-tests` which was set in https://github.com/apache/incubator-pekko-grpc/pull/64. In order to verify there …
> Create NoPublish sbt plugin

- plugin-tester-scala/src/test/scala/example/myapp/helloworld/ErrorReportingSpec.scala
This implicit without a type declaration is causing major CI build problems.
Oddly the fails here are in the 2.13 builds but they do relate to this untyped implicit. https://github.com/apache/incubator-pekko-grpc/pull/90/checks
> compile issue - now that we support Scala 3

- .github/workflows/build-test.yml
* wrong matrix set
* the place where the 3.3 was added was for sbt plugin testing and sbt plugin only needs scala 2.12 testing
* we are missing scala 3.3 testing of runtime code
> run right scala 3 tests

- build.sbt
- docs/src/main/paradox/server/grpc-web.md
- plugin-tester-java/build.gradle
- plugin-tester-java/pom.xml
- plugin-tester-scala/build.gradle
- plugin-tester-scala/pom.xml
- project/Dependencies.scala
- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/WebHandler.scala
- runtime/src/main/scala/org/apache/pekko/grpc/scaladsl/WebHandler.scala
- sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
- sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt
- sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt
- sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt
- sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/build.sbt
- sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
Also removes the now unnecessary Snapshot OSS repo, removes other workarounds and updates pekko core to 1.0.0-RC3.
> Update latest pekko-http to bring in cors

- runtime/src/main/scala/org/apache/pekko/grpc/GrpcClientSettings.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/RequestBuilderImpl.scala
* the text is consistent with existing deprecation versions (that also use 'akka-grpc')
> ensure old akka-grpc deprecation versions are specified to be akka-grpc

- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPlugin.groovy
The original reason behind this repository being there is its used to resolve akka-grpc snapshot versions which were deployed to OSS sonatype. In https://github.com/apache/incubator-pekko-grpc/pull/23 we added more repos so that pekko-grpc could build with both akka (before akka/akka-http was even published as a snapshot) but since all dependencies are now properly released and we are not relying on akka artifacts anymore ideally we should only have a single `https://repository.apache.org/content/groups/snapshots` (which is our equivalent of `https://oss.sonatype.org/content/repositories/snapshots`), just like it was before we started working on the original akka-grpc branch.
> Remove redundant oss sonatype snapshots repo

- docs/src/main/paradox/buildtools/gradle.md
* we don't yet have a way to publish the plugin to Gradle Plugins portal
* to unblock the pekko-grpc release, document how to build the plugin locally and how to consume it
> document how to use the gradle plugin

- .github/workflows/publish-nightly.yml
- gradle-plugin/build.gradle
References: https://github.com/apache/incubator-pekko-grpc/issues/113
Only thing that is missing is signing (see https://github.com/gradle-nexus/publish-plugin#configure-signing) but lets do that separately.
> Setup gradle plugin for publishing

- gradle-plugin/build.gradle
The previously entered URI is wrong, instead should have `/service/local` at the end (i.e. Apache equivalent of https://github.com/gradle-nexus/publish-plugin/blob/b116c25e9271734341be8078ab264b70e87f51cc/src/main/kotlin/io/github/gradlenexus/publishplugin/DefaultNexusRepositoryContainer.kt#L37)
References: https://github.com/apache/incubator-pekko-grpc/issues/113
> Fix grpc gradle sonatype publish uri

- .github/workflows/build-test.yml
- .github/workflows/publish-nightly.yml
- gradle-plugin/build.gradle
- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPlugin.groovy
- plugin-tester-java/settings.gradle
So I can confirm that the reason behind the gradle plugin not building correctly is that it wasn't setting the version correctly (see https://github.com/apache/incubator-pekko-grpc/actions/runs/5786987516/job/15682898907). After spending the last few hours digging around to figure out how gradle publishing works I came up with an elegant solution that also simplifies whats going on.
Currently the gradle version is manually derived from executing git and parsing the results. Not only is this quite brittle (the sed regex would fail once we start releasing RC's/milestones for this same reason https://github.com/apache/incubator-pekko-http/issues/293#issuecomment-1666861760) but it also requires quite a bit of boilerplate because every single time we need to publish the gradle plugin (whether …
> Derive gradle version from sbt

- .github/workflows/publish-nightly.yml
- README.md
- docs/src/main/paradox/buildtools/gradle.md
- docs/src/main/paradox/release-notes/index.md
- docs/src/main/paradox/server/walkthrough.md
- plugin-tester-scala/settings.gradle
The Gradle plugin now successfully deploys to maven central, see https://github.com/apache/incubator-pekko-grpc/actions/runs/5789438448/job/15690488703. The PR updates the documentation and also updates all references from `gradlePluginPortal`.
Resolves: https://github.com/apache/incubator-pekko-grpc/issues/113.
> Update references of gradlePluginPortal to mavenCentral

- gradle-plugin/build.gradle
I havent tried this out yet, mainly just used the instructions from https://docs.gradle.org/current/userguide/signing_plugin.html#sec:signing_publications but I suspect we will find out if the signing works when we get there.
> Add signing for release artifacts

- gradle-plugin/build.gradle
- gradle-plugin/settings.gradle
- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPlugin.groovy
- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy
- gradle-plugin/src/test/groovy/func/GradleCompatibilitySpec.groovy
- gradle-plugin/src/test/groovy/helper/BaseSpec.groovy
- gradle-plugin/src/test/groovy/helper/ScalaWrapperPlugin.groovy
- gradle-plugin/src/test/groovy/unit/ApplySpec.groovy
- gradle-plugin/src/test/groovy/unit/DependenciesSpec.groovy
- plugin-tester-java/build.gradle
- plugin-tester-java/settings.gradle
- plugin-tester-scala/build.gradle
- plugin-tester-scala/settings.gradle
Files that were originally written by Akka team are given a non-standard Apache license header.
> use LEGAL-626 license header

- plugin-tester-java/pom.xml
- plugin-tester-scala/pom.xml
The header should go after the XML declaration - eg https://github.com/apache/hadoop/blob/trunk/pom.xml
> add LEGAL-626 header to pom.xml files

- gradle-plugin/build.gradle
Release mangers will need to set up their `~/.gradle/gradle.properties` when creating a release candidate.
* https://docs.gradle.org/6.9.1/userguide/signing_plugin.html#sec:conditional_signing
They will need to add these props but correct the values to match their gpg setup.
```
signing.keyId=24875D73
signing.password=secret
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg
```
> get jar signing to work

- build.sbt
- docs/src/main/paradox/release-notes/index.md
- sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-java/03-no-java-package/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/project/plugins.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/project/plugins.sbt
- sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/plugins.sbt
Currently the artifact name for the sbt plugin is inconsistent with the other artifacts that pekko-grpc generates, i.e. currently the sbt artifact name is `sbt-pekko-grpc` where as all other artifacts start with `pekko-grpc-<REST>`. This even includes the other build tool plugins that pekko-grpc provides, i.e. `pekko-grpc-gradle-plugin`/`pekko-grpc-maven-plugin`
> Rename sbt plugin artifact so it's consistent with other artifacts

- project/Dependencies.scala
grpc lib uses a newer version of protobuf-java (3.21.1) then we set (3.20.3) but this has CVEs
> upgrade protobuf-java to 3.21.12

- benchmark-java/project/build.properties
- build.sbt
- project/build.properties
- sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/project/build.properties
- sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/build.properties
- sbt-plugin/src/sbt-test/gen-java/03-no-java-package/project/build.properties
- sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/project/build.properties
- sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/project/build.properties
- sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/project/build.properties
- sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/build.properties
Trick I got from https://github.com/sbt/sbt-github-actions/pull/163#discussion_r1327598500
> Update to SBT 1.9.6 and remove build.properties boilerplate

- build.sbt
based on how this is set in akka-grpc (at the time we split out pekko)
> re-enable mima checks

- runtime/src/main/scala/org/apache/pekko/grpc/internal/NettyClientUtils.scala
Reverts apache/incubator-pekko-grpc#197
the OP of apache/incubator-pekko-grpc#197 copied license incompatible code from akka-grpc - completely unacceptable
the code might be short but the OP kept the comments exactly the same as the akka comments making it obvious that the code is not his
Pekko contributors - anyone else who reads the akka-grpc code will become unavailable to review or contribute to fixing the original issue
We need a clean room fix.
> Revert "[Netty] Fix client with TLS and custom SSL context"

- .github/workflows/build-test.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-nightly.yml
- plugin-tester-java/build.gradle
- plugin-tester-scala/build.gradle
- plugin-tester-scala/pom.xml
- project/Dependencies.scala
- project/plugins.sbt
> upgrade pekko and build tool versions

- runtime/src/main/scala/org/apache/pekko/grpc/internal/NettyClientUtils.scala
see #197 and #199 
the akka-grpc 2.1.6 breakage was traced back to this OSS akka-grpc 2.1.6 change (https://github.com/akka/akka-grpc/pull/1649) and reverted here
> revert grpc breaking netty tls change

- build.sbt
- project/Dependencies.scala
- project/plugins.sbt
need to be able to test with different builds
> use sbt-pekko-build to allow testing with pekko/pekko-http snapshots

- interop-tests/src/test/scala/org/apache/pekko/grpc/interop/GrpcInteropSpec.scala
- interop-tests/src/test/scala/org/apache/pekko/grpc/interop/PekkoGrpcScalaClientTester.scala
The new tests in GrpcInteropIoWithPekkoNettyScalaWithSslContextSpec fail without the fix in #199
> test with sslcontext

- .github/workflows/nightly-snapshot-dependency-test.yml
> Nightly job to test with Pekko/Pekko-HTTP snapshots

- gradle-plugin/build.gradle
> Close gradle build stream in finally block

- project/CopyrightHeader.scala
- project/Dependencies.scala
- project/NoPublish.scala
- project/ReflectiveCodeGen.scala
- project/SbtMavenPlugin.scala
- project/VersionGenerator.scala
Should improve the sbt build speed a little bit by avoiding unnecessary computation
> Use lazy val in build for zero args defs plus sbt dsl

- build.sbt
- gradle-plugin/build.gradle
use `gRPC` to match the usual style
> change pom name

- build.sbt
issue is that previousStableVersion only looks at git tags and we have a v1.1.0-M0 git tag but no release of that name
> mima comparison failing

- .github/workflows/build-test.yml
- .github/workflows/publish-1.0-nightly.yml
- .github/workflows/publish-nightly.yml
- plugin-tester-java/build.gradle
- plugin-tester-scala/build.gradle
- sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt
- sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt
- sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt
- sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt
- sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt
- sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt
* upgrade scala versions
* upgrade CI actions
* add memory setting in CI build
> upgrade build

- gradle-plugin/build.gradle
- project/Dependencies.scala
the old guava version hack was down to Pekko-gRPC 1.0 and our attempt to use an out of date io.grpc jar but to use a newer guava jar because of a CVE in the old guava version
We now use up to date io.gprc jar so it will have a newer guava dependency.
See dependencies in https://mvnrepository.com/artifact/io.grpc/grpc-protobuf/1.62.2
> remove guava upgrade hack

- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy
- maven-plugin/src/main/maven/plugin.xml
- project/Dependencies.scala
scala-steward doesn't upgrade protoc
> upgrade protobuf/protoc to 3.25.3

- interop-tests/src/test/java/org/apache/pekko/grpc/interop/PekkoGrpcJavaClientTester.java
- interop-tests/src/test/scala/org/apache/pekko/grpc/interop/GrpcInteropSpec.scala
close #204 
according to PekkoGrpcScalaClientTester
(1) add `backend` for `PekkoGrpcJavaClientTester` so that we can config 'pekko-http' and netty
(2) add `testWithSslContext` for `PekkoGrpcJavaClientTester`
> enable GrpcInteropIoWithPekkoHttpJavaSpec to work

- docs/src/main/paradox/server/details.md
- interop-tests/src/test/scala/org/apache/pekko/grpc/scaladsl/GrpcExceptionDefaultHandleSpec.scala
- runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/GrpcExceptionHandlerSpec.scala
close #291 
maybe : there are 2 file-name(class) used GrpcExceptionHandlerSpec with same package
and `new NullPointerException` shoulde be `new NullPointerException()`
> Investigate a frequently flaky CI failure in GrpcExceptionHandlerSpec

- interop-tests/src/test/java/example/myapp/helloworld/grpc/RichErrorModelTest.java
close #291 
client should wait http server start, and need to stop http finally.
add wait and stop
> fix flaky failure in CI for RichErrorModelTest

- plugin-tester-java/src/main/java/example/myapp/helloworld/LoggingErrorHandlingGreeterClient.java
in module `plugin-tester-scala`
there are `LoggingErrorHandlingGreeterServer` and `LoggingErrorHandlingGreeterClient`
but in moulde `plugin-tester-java`
there is not a `LoggingErrorHandlingGreeterClient`
add  LoggingErrorHandlingGreeterClient with java
NOW, we run a Scala-server, use java-client to sayHello, interesting play with it.
> add LoggingErrorHandlingGreeterClient with java

- runtime/src/test/scala/org/apache/pekko/grpc/scaladsl/headers/HeadersSpec.scala
can't execute sbt scalafmtAll
```
invalid unicode surrogate pair
[error]         ("my favorite character is \ud801", "my favorite character is ?")
```
according to test in grpc-java, we should use 0xD801.toChar
https://github.com/grpc/grpc-java/blob/79e75bace40cea7e4be72e7dcd1f41c3ad6ee857/api/src/test/java/io/grpc/StatusTest.java#L82-L92
> chore:fix scalafmt HeadersSpec error because illegal unicode

- build.sbt
see #298 
also try to tidy up a reference to 10.2.0 - which was an Akka HTTP release
> try to fix broken links

- docs/src/main/paradox/server/pekko-http.md
docs say 10.2 but this is not a Pekko HTTP version number
> make Akka version obvious

- runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtils.scala
- runtime/src/test/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtilsSpec.scala
In #230 I introduced a bug in the trailer decoding where I didn't take into consideration that there are "ASCII headers" and "binary headers"
> fix binary trailer decoding

- docs/src/main/paradox/server/details.md
- interop-tests/src/main/java/io/grpc/testing/integration2/TestServiceClient.java
- plugin-tester-java/src/main/java/example/myapp/CombinedServer.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/GreeterClient.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/GreeterServer.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/GreeterServiceImpl.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/GreeterServicePowerApiImpl.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/LiftedGreeterClient.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/LoggingErrorHandlingGreeterServer.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/PowerGreeterServer.java
- plugin-tester-java/src/main/java/example/myapp/helloworld/PowerGreeterServiceImpl.java
- plugin-tester-scala/src/test/scala/example/myapp/helloworld/GreeterServiceSpec.scala
There are some unnecessary variable and style in `plugin-tester-Java` that does not use variables. I have readed the code for these two modules. clean up the code
plugin-tester-scala.
BTW, PowerGreeterServer and PowerGreeterServer lost the client, it will be an another PR later.
clean up
> Refactoring code in plugin-tester-java(scala)

- runtime/src/main/scala/org/apache/pekko/grpc/internal/Gzip.scala
> use ByteString.toArrayUnsafe

- runtime/src/main/scala/org/apache/pekko/grpc/internal/ByteStringInputStream.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/Gzip.scala
> use ByteStringInputStream

- .github/workflows/build-test.yml
- .github/workflows/publish-nightly.yml
- project/Dependencies.scala
see #319 - scala steward is broken
> scala 2.13.14

- build.sbt
And make the dependency tree leaner.
Fixes #325 (though the use case is still somewhat unclear)
> Publish `pekko-grpc-scalaph-protoc-plugin` for Scala 2.13

- CONTRIBUTING.md
Update some outdated/missing bits
> feat: improve contributing docs

- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/GrpcExceptionHandler.scala
- runtime/src/main/scala/org/apache/pekko/grpc/scaladsl/GrpcExceptionHandler.scala
The `GrpcExceptionHandler` logs `PeerClosedStreamException` as an error. This is causing log spam in cloud environments where clients abruptly terminate. The exception should be logged as a warning instead.
> Log PeerClosedStreamExceptions as warnings instead of errors

- plugin-tester-java/build.gradle
- plugin-tester-scala/build.gradle
- plugin-tester-scala/pom.xml
- project/Dependencies.scala
- project/PekkoCoreDependency.scala
> pekko 1.1.1

- gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy
- maven-plugin/src/main/maven/plugin.xml
- project/Dependencies.scala
changes missed in https://github.com/apache/pekko-grpc/pull/350
> protobuf 3.25.4

- .github/workflows/build-test.yml
- .github/workflows/publish-nightly.yml
- project/Dependencies.scala
seems ok to upgrade now
build issues are just in link-validator and those issues are explainable (gnu.org is offline and lightbemd.com page works but link-validator seems to be having issues with it in a few builds)
> scala 2.13.15 and 3.3.4

- .github/workflows/build-test.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-snapshot-dependency-test.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.0-nightly.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
see https://github.com/apache/pekko-http/pull/619
> CI: setup-sbt

- interop-tests/src/test/scala/org/apache/pekko/grpc/interop/PekkoHttpServerProviderScala.scala
- interop-tests/src/test/scala/org/apache/pekko/grpc/scaladsl/GrpcExceptionDefaultHandleSpec.scala
- project/PekkoHttpDependency.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/GrpcEntityHelpers.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/GrpcResponseHelpers.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoNettyGrpcClientGraphStage.scala
- sbt-plugin/src/sbt-test/gen-scala-server/00-interop/src/test/scala/org/apache/pekko/grpc/GrpcInteropSpec.scala
Attempt to fix https://github.com/apache/pekko-grpc/issues/392
> Merge grpc headers and trailers in case of failure

- runtime/src/main/scala/org/apache/pekko/grpc/internal/GrpcResponseHelpers.scala
I missed a case in https://github.com/apache/pekko-grpc/pull/391
> Apply trailer only optimization for responseForSingleElement

- maven-plugin/src/main/scala/org/apache/pekko/grpc/maven/AbstractGenerateMojo.scala
* `asScala` is used in 2 places
- in one case, we add a locally scoped import on Scala JavaConverters
- in the other case, we have a globally scoped import on Scala JavaConverters but in the middle of the class
* I've moved the globally scoped one to be local to the 2nd use of `asScala`
> tidy up imports

- build.sbt
see #404 - plugin-tester-java and interop-tests set this - so best to be consistent
> plugin-tester-scala: set protoc version

- runtime/src/main/scala/org/apache/pekko/grpc/internal/CancellationBarrierGraphStage.scala
Motivation:
Fuse the inHandler and outHandler to reduce memory usage.
> chore: fuse handlers in CancellationBarrierGraphStage

- .github/workflows/build-test.yml
- .github/workflows/format.yml
- .github/workflows/headers.yml
- .github/workflows/link-validator.yml
- .github/workflows/nightly-snapshot-dependency-test.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/publish-1.0-docs.yml
- .github/workflows/publish-1.0-nightly.yml
- .github/workflows/publish-1.1-docs.yml
- .github/workflows/publish-nightly.yml
- .github/workflows/scala-steward.yml
header depends on whether the initial work is from Pekko times or if the yml is based on work that we inherited from Akka
> CI: add source headers

- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/GrpcMarshalling.scala
- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/package.scala
* some of the wrapping may only have been needed in Scala 2.11
* tidy up related to #483 but this change is safe for a 1.3.0 release
> remove function wrapping and deprecate unused function wrapping functions

- build.sbt
The automated Scala Steward PRs don't update this value.
> Update scriptedSbt version from 1.11.3 to 1.11.5

- .github/workflows/nightly-snapshot-dependency-test.yml
* Pekko 2 is matching 'main' and that has breaking build changes
* Safer to test with latest 1.2.x snapshots
* https://github.com/apache/pekko-grpc/actions/workflows/nightly-snapshot-dependency-test.yml
> use 1.2.x snapshots in nightly test workflow

- runtime/src/main/scala/org/apache/pekko/grpc/GrpcChannel.scala
- runtime/src/main/scala/org/apache/pekko/grpc/GrpcClientSettings.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/MetadataImpl.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtils.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoNettyGrpcClientGraphStage.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/RequestBuilderImpl.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/SingleParameterSink.scala
- runtime/src/main/scala/org/apache/pekko/grpc/internal/UnaryCallAdapter.scala
- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/ServerReflection.scala
- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/WebHandler.scala
- runtime/src/main/scala/org/apache/pekko/grpc/scaladsl/Grpc.scala
* with scala 2.12 no longer supported in runtime modules for pekko 2.0.0, we can now use Scala built-in converters
> use scala converters

- runtime/src/main/scala/org/apache/pekko/grpc/internal/MetadataImpl.scala
the old code documents that this new code is what we should use - and now that Scala 2.12 support is gone, we can change
> use groupMap

- runtime/src/main/scala/org/apache/pekko/grpc/internal/MetadataImpl.scala
when converting a Scala to Java conversion of Map with a value type that is Seq (that we want to convert to a Java List), we don't want to run a map function on each value seq to cast the type. We can just cast the Seq so change the type.
> [WIP] try to avoid unnecessary step in map conversion

- runtime/src/main/scala/org/apache/pekko/grpc/javadsl/ServerReflection.scala
* Similar to #520 
* It is hard to avoid doing various map calls on Scala monadic types when converting to Java DSL
* In many cases, the wrapped element(s) are from a class that implements both the Scala and Java DSL APIs so while the return looks like `JavaMonadicType<javadsl.ElementType>` and we start with `ScalaMonadicType[scaladsl.ElementType]` - we do need to change the MonadicType (eg Scala Future to Java CompletionStage) but we don't run a map function to cast the scaladsl.ElementType to javaadsl.ElementType. We can just run a higher level cast, eg cast from  `JavaMonadicType<scaladsl.ElementType>` to `JavaMonadicType<javadsl.ElementType>`
> try to avoid unnecessary map conversions in Java DSL
