.asf.yaml
Looking kind of silly right now -_-, didn't notice the nesting was wrong
=> Actually properly remove branch protection

.github/release-drafter.yml, .github/workflows/build-test.yml, .github/workflows/format.yml, .github/workflows/link-validator.yml, .github/workflows/pr-labeler.yml, .github/workflows/publish.yml
* related to https://github.com/apache/incubator-pekko-grpc/pull/12
* also fix issue where some CI workflows are not properly enabled (akka-grpc is hardcoded in them)
=> upgrade to TimonVS/pr-labeler-action@v4

.github/workflows/build-test.yml
https://github.com/apache/incubator-pekko-grpc/issues/24
=> add back CI headerCheckAll

build.sbt, project/plugins.sbt, project/project-info.conf
Working as expected, thanks to @jrudolph for solving the circe binary compatibility issue
=> Use Pekko Paradox sbt plugin

.asf.yaml
=> Add scalafmt to required status check

.github/workflows/build-test.yml, .github/workflows/publish.yml, .jvmopts-ci, .jvmopts-ghactions
This PR is intended to fix the currently broken publish step. Note that the PR currently disables publishing the `gradle-plugin` (see https://github.com/apache/incubator-pekko-grpc/issues/40) and will be fixed later once resolved. The PR also disables publishing docs, this needs to be implemented our way.
Resolves: https://github.com/apache/incubator-pekko-grpc/issues/29
=> Fix publish

project/Common.scala, project/plugins.sbt
Replaces ci-release with dynver, see https://lists.apache.org/thread/l7yp8yb2ooy7opwmzpw7hkmz9gm0qr2r
=> Replace ci-release with dynver

plugin-tester-java/build.gradle, plugin-tester-scala/build.gradle, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt, sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt, sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt, sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt, sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/build.sbt
Updates scala versions to their latest
=> Update scala versions

plugin-tester-java/build.gradle, plugin-tester-scala/build.gradle, plugin-tester-scala/pom.xml, project/Dependencies.scala
Needed for https://github.com/apache/incubator-pekko-projection/pull/19
=> Update pekko snapshot

.github/workflows/build-test.yml, .github/workflows/headers.yml
Split header check into its own github workflow
=> Split header check into its own github workflow

build.sbt, plugin-tester-java/build.gradle, plugin-tester-java/pom.xml, plugin-tester-scala/build.gradle, plugin-tester-scala/pom.xml, project/Dependencies.scala
So we don't miss it when a release is made
=> Add in TODOs for future code revisions

CONTRIBUTING.md, README.md, codegen/src/main/scala/org/apache/pekko/grpc/gen/scaladsl/ScalaMarshallersCodeGenerator.scala, docs/src/main/paradox/getting-started.md, interop-tests/src/main/scala/io/grpc/testing/integration2/ChannelBuilder.scala, interop-tests/src/test/scala/org/apache/pekko/grpc/interop/PekkoHttpServerProviderScala.scala, project/Common.scala, project/Dependencies.scala, runtime/src/main/scala/org/apache/pekko/grpc/GrpcClientSettings.scala, runtime/src/test/scala/org/apache/pekko/grpc/GrpcClientSettingsSpec.scala, runtime/src/test/scala/org/apache/pekko/grpc/internal/PekkoDiscoveryNameResolverProviderSpec.scala, runtime/src/test/scala/org/apache/pekko/grpc/internal/PekkoDiscoveryNameResolverSpec.scala, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/src/test/scala/org/apache/pekko/grpc/GrpcInteropSpec.scala
follow up to https://github.com/apache/incubator-pekko-grpc/pull/57
=> more pekko naming issues

.github/actions/sync-nightlies/action.yml, .github/workflows/publish.yml
grpc docs are linked to from the main pekko docs - useful to have these docs published so the links work
=> publish grpc docs to nightlies.apache.org

plugin-tester-java/build.gradle, plugin-tester-scala/build.gradle, plugin-tester-scala/pom.xml, project/Dependencies.scala, runtime/src/main/scala/org/apache/pekko/grpc/GrpcChannel.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/MetadataImpl.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtils.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoNettyGrpcClientGraphStage.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/RequestBuilderImpl.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/SingleParameterSink.scala, runtime/src/main/scala/org/apache/pekko/grpc/internal/UnaryCallAdapter.scala, runtime/src/main/scala/org/apache/pekko/grpc/javadsl/ServerReflection.scala, runtime/src/main/scala/org/apache/pekko/grpc/javadsl/WebHandler.scala
Unlike with pekko-http, this one was fairly trivial.
=> Apply compat changes from latest Pekko

runtime/src/main/scala/org/apache/pekko/grpc/GrpcClientSettings.scala, runtime/src/main/scala/org/apache/pekko/grpc/ServiceDescription.scala
Something that I quickly noticed, death to the semicolons
=> Remove redundant semicolons

build.sbt
References: https://github.com/apache/incubator-pekko-grpc/issues/77
=> Skip doc publish for plugin-tester

plugin-tester-java/build.gradle, plugin-tester-scala/build.gradle, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt, sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt, sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt, sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt, sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/build.sbt
=> Update Scala 2 versions

.github/workflows/link-validator.yml, build.sbt, docs/src/main/paradox/apidesign.md, docs/src/main/paradox/buildtools/gradle.md, docs/src/main/paradox/client/details.md, docs/src/main/paradox/overview.md, docs/src/main/paradox/proto.md, docs/src/main/paradox/server/details.md, docs/src/main/paradox/server/kubernetes.md, docs/src/main/paradox/server/pekko-http.md, project/project-info.conf, scripts/link-validator.conf
* all link validation runs fail at the moment
* fix up broken links
=> use coursier github actions

project/CopyrightHeader.scala, project/MetaInfLicenseNoticeCopy.scala, project/NoPublish.scala
Same as https://github.com/apache/incubator-pekko/pull/474 but for this repo
=> Apply normal apache header new files

build.sbt, plugin-tester-java/build.gradle, plugin-tester-java/pom.xml, plugin-tester-scala/build.gradle, plugin-tester-scala/pom.xml, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/build.sbt, sbt-plugin/src/sbt-test/gen-java/02-server-reflection/build.sbt, sbt-plugin/src/sbt-test/gen-java/03-no-java-package/build.sbt, sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/build.sbt, sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/build.sbt, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt, sbt-plugin/src/sbt-test/scala3/01-basic-client-server/build.sbt
use pekko 1.0.0 - and a pekko-http that was built with pekko 1.0.0
=> pekko 1.0.0 release

build.sbt, project/plugins.sbt
see https://github.com/apache/incubator-pekko/pull/468
=> source dist name

gradle-plugin/build.gradle
=> add license to gradle plugin jar

docs/src/main/paradox/server/pekko-http.md, interop-tests/src/main/scala/io/grpc/testing/integration2/Settings.scala
=> some stray akka refs

CONTRIBUTING.md
* I updated this in error - https does not work on this link
=> fix incorrect change in CONTRIBUTING.md

README.md
=> building from source

.github/workflows/publish-nightly.yml, gradle-plugin/build.gradle
=> Log incase of missing environment variables

gradle-plugin/build.gradle, gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle-plugin/gradlew.properties, gradle-plugin/settings.gradle, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPlugin.groovy, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy, gradle-plugin/src/test/groovy/func/GradleCompatibilitySpec.groovy, gradle-plugin/src/test/groovy/helper/BaseSpec.groovy, gradle-plugin/src/test/groovy/helper/ScalaWrapperPlugin.groovy, gradle-plugin/src/test/groovy/unit/ApplySpec.groovy, gradle-plugin/src/test/groovy/unit/DependenciesSpec.groovy, plugin-tester-java/build.gradle, plugin-tester-java/settings.gradle, plugin-tester-scala/build.gradle, plugin-tester-scala/settings.gradle
I picked this up when working on the gradle stuff
=> Add headers to gradle build source files

LICENSE, legal/RuntimeLicense.txt
These files are Apache licensed but have grpc copyrights
=> add refs to proto files in LICENSE

benchmark-java/project/plugins.sbt, docs/src/main/paradox/client/walkthrough.md, docs/src/main/paradox/server/walkthrough.md
some docs/comments missed in recent sbt plugin name change
=> fix sbt plugin docs

.github/workflows/publish-1.0-docs.yml, .github/workflows/publish-nightly.yml
based on how we do this in pekko core repo
=> publish 1.0 docs

gradle-plugin/build.gradle
https://docs.gradle.org/current/userguide/working_with_files.html#sec:reproducible_archives
=> steps towards making gradle build reproducible

gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle-plugin/src/test/groovy/func/GradleCompatibilitySpec.groovy, plugin-tester-java/gradle/wrapper/gradle-wrapper.properties, plugin-tester-scala/gradle/wrapper/gradle-wrapper.properties
Latest version in the 6.9.1 series so it should work fine.
=> Update gradle to 6.9.1

benchmark-java/project/build.properties, project/Common.scala, project/build.properties, project/plugins.sbt, sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/project/build.properties, sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/build.properties, sbt-plugin/src/sbt-test/gen-java/03-no-java-package/project/build.properties, sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/project/build.properties, sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/project/build.properties, sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/build.properties
=> use sbt paradox release

benchmark-java/build.sbt, build.sbt, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy, plugin-tester-java/pom.xml, plugin-tester-scala/pom.xml, project/Dependencies.scala, project/plugins.sbt, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
=> upgrade grpc-protobuf due to CVEs

gradle-plugin/build.gradle
Generally upgrading protobuf for next pekko-grpc relaese
=> protobuf-gradle-plugin 0.9.4

gradle-plugin/build.gradle, project/Dependencies.scala, scripts/link-validator.conf
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2976
=> use newer version of guava due to CVE

benchmark-java/project/build.properties, build.sbt, project/build.properties, sbt-plugin/src/sbt-test/gen-java/01-gen-basic-java/project/build.properties, sbt-plugin/src/sbt-test/gen-java/02-server-reflection/project/build.properties, sbt-plugin/src/sbt-test/gen-java/03-no-java-package/project/build.properties, sbt-plugin/src/sbt-test/gen-java/04-crash-on-keywords/project/build.properties, sbt-plugin/src/sbt-test/gen-java/05-duplicate-messages-different-packages/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/01-gen-basic-server/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/03-test-config/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/05-no-java-package/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/06-compatibility-plugins/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/07-gen-basic-server-with-pekko/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/09-scalapb-customizations/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/10-scalapb-validate/project/build.properties, sbt-plugin/src/sbt-test/gen-scala-server/11-duplicate-messages-different-packages/project/build.properties, sbt-plugin/src/sbt-test/scala3/01-basic-client-server/project/build.properties
SBT 1.9.5. added the `Resolver.ApacheMavenStagingRepo` constant
=> Update to SBT 1.9.5 and use Apache Staging repo constant

sbt-plugin/src/sbt-test/gen-scala-server/02-multiple-services/src/main/scala/example/myapp/Main.scala, sbt-plugin/src/sbt-test/gen-scala-server/04-server-reflection/src/main/scala/example/myapp/helloworld/Main.scala
deprecated and not needed any more
=> remove ActorMaterializer

build.sbt, project/Dependencies.scala
we've been changing these links in other modules
=> change doc links to 1.0

runtime/src/main/scala/org/apache/pekko/grpc/internal/NettyClientUtils.scala
Fixes https://github.com/playframework/play-grpc/issues/468
=> [Netty] Fix client with TLS and custom SSL context

codegen/src/main/scala/org/apache/pekko/grpc/gen/javadsl/JavaClientCodeGenerator.scala, codegen/src/main/scala/org/apache/pekko/grpc/gen/scaladsl/ScalaClientCodeGenerator.scala, plugin-tester-scala/README.md, plugin-tester-scala/src/main/scala/example/myapp/helloworld/AuthenticatedGreeterClient.scala, plugin-tester-scala/src/main/scala/example/myapp/helloworld/GreeterClient.scala, plugin-tester-scala/src/main/scala/example/myapp/helloworld/LoggingErrorHandlingGreeterClient.scala, runtime/src/main/scala/org/apache/pekko/grpc/GrpcClientSettings.scala
=> akka to pekko naming

NOTICE
see https://github.com/apache/incubator-pekko/pull/1009
=> add incubating to NOTICE

.github/workflows/nightly-snapshot-dependency-test.yml, .github/workflows/publish-nightly.yml
Motivation:
Stream line the build.
=> chore: Schedule build at 2 AM

.github/workflows/headers.yml, .github/workflows/link-validator.yml
see https://github.com/apache/incubator-pekko/pull/1095
=> upgrade coursier/cache-action

.github/workflows/link-validator.yml
see https://github.com/apache/incubator-pekko/pull/1104
=> upgrade action in link-validator.yml

runtime/src/main/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtils.scala, runtime/src/test/scala/org/apache/pekko/grpc/internal/PekkoHttpClientUtilsSpec.scala
When using the pekko-http backend and a `StatusRuntimeException` is returned it lacks metadata. 
This PR fixes the case for both headers and trailers
The issue was initially reported in https://github.com/akka/akka-grpc/issues/1814 and I fixed it myself in akka-grpc
=> make sure trailers are present in StatusRuntimeException

.github/workflows/pr-labeler.yml
Node 16 warnings should be fixed by upgrading
=> upgrade actions in pr-labeler.yml

build.sbt
cherry pick fba87430aa4484afec8271d454528cb413f321b2 #234
=> fix build interpolation (#234)

project/plugins.sbt
(cherry picked from commit e0346183551a5f9a2597557cf9cd20b3e5fb71e5)
=> fix logo / favicon issue (#236)

project/plugins.sbt
=> scalapb 0.11.15

project/Dependencies.scala
(cherry picked from commit 28aeac7f24b5e3eaf707c3aa39879fb602a7fe23)
=> upgrade scala (#240)

.github/workflows/publish-1.0-docs.yml, .jvmopts-ci
failing with memory issues
https://github.com/apache/pekko-grpc/actions/runs/8429793439
=> set Xmx for nightly jobs

build.sbt
see https://github.com/apache/pekko-grpc/actions/runs/8304583091/job/22730386156
=> snapshot resolver needed so nightly tests can use pekko snapshots

build.sbt
cherry pick de6f18dd4e2a42a7c3e809212e08f2cc7878a5d8 #250
=> remove incubator footer (#250)

.scala-steward.conf
=> Avoid upgrading grpc-java

.scala-steward.conf
=> Pin protobuf to 3.x

runtime/src/main/scala/org/apache/pekko/grpc/internal/Codecs.scala
Removed an unnecessary Set[CodeName] in Codec
clean up
test locally
=> Refactoring some code of Codec

docs/src/main/paradox/server/reflection.md
fix the issue link, and the issue is open in akka-grpc
=> chore:fix an incorrect issue link  on reflection page

build.sbt
cherry pick aa55b8134da792d58db517e2fb0abc5f966da3c3 #299
=> try to fix broken links (#299)

.scala-steward.conf, benchmark-java/build.sbt, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy, plugin-tester-java/pom.xml, plugin-tester-scala/pom.xml, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
=> grpc 1.64.0

docs/src/main/paradox/release-notes/index.md, docs/src/main/paradox/release-notes/releases-1.0.md, docs/src/main/paradox/release-notes/releases-1.1.md
will merge after release vote passes
=> release notes for 1.1

codegen/src/main/scala/org/apache/pekko/grpc/gen/javadsl/Method.scala, sbt-plugin/src/sbt-test/gen-java/06-nested-message/build.sbt, sbt-plugin/src/sbt-test/gen-java/06-nested-message/project/plugins.sbt, sbt-plugin/src/sbt-test/gen-java/06-nested-message/src/main/java/org/example/service/v1/impl/TestGrpcsServiceImpl.java, sbt-plugin/src/sbt-test/gen-java/06-nested-message/src/main/protobuf/test.proto, sbt-plugin/src/sbt-test/gen-java/06-nested-message/test
=> fix: codegen: java: nested protobuf message types

gradle-plugin/gradle/wrapper/gradle-wrapper.properties, gradle-plugin/src/test/groovy/func/GradleCompatibilitySpec.groovy, plugin-tester-java/gradle/wrapper/gradle-wrapper.properties, plugin-tester-scala/gradle/wrapper/gradle-wrapper.properties
multiple useful bug fixes and dependency updates
https://docs.gradle.org/7.6.4/release-notes.html
=> gradle 7.6.4

project/PekkoHttpDependency.scala
last change needed before RC made for pekko-gprc 1.1.0
=> pekko http 1.1.0 release

.github/workflows/publish-1.1-docs.yml, docs/src/main/paradox/release-notes/releases-1.1.md
=> release notes for 1.1.0

build.sbt, project/Dependencies.scala
see https://github.com/apache/pekko-connectors-kafka/pull/241
=> use addPekkoModuleDependency

.scala-steward.conf, benchmark-java/build.sbt, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy, plugin-tester-java/pom.xml, plugin-tester-scala/pom.xml, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
* issues with 1.68.1 (see #397)
* the 1.68.0 release seems to have been a mistake - https://github.com/grpc/grpc-java/releases/tag/v1.68.0
=> grpc 1.67.1

.github/workflows/publish-1.1-docs.yml, docs/src/main/paradox/release-notes/releases-1.1.md
=> release notes for 1.1.1

.scala-steward.conf, benchmark-java/build.sbt, gradle-plugin/src/main/groovy/org/apache/pekko/grpc/gradle/PekkoGrpcPluginExtension.groovy, plugin-tester-java/pom.xml, plugin-tester-scala/pom.xml, project/Dependencies.scala, sbt-plugin/src/sbt-test/gen-scala-server/00-interop/build.sbt
(to see CI results, follow-up on #402)
=> grpc: update to 1.68.2

.github/workflows/build-test.yml, .github/workflows/publish-nightly.yml, project/Dependencies.scala
scala steward job failed because we don't allow it to edit or CI yml
=> scala 2.13.16

.github/workflows/build-test.yml, .github/workflows/publish-nightly.yml
=> upgrade CI to use scala 3.3.5

.scala-steward.conf
=> Pin sbt-java-formatter to 0.9.x

.asf.yaml, .github/workflows/publish-1.0-snapshots.yml, .github/workflows/publish-1.1-docs.yml, .github/workflows/publish-1.1-nightly.yml, .github/workflows/publish-1.1-snapshots.yml
we have a 1.2 change ready for merge
=> protect 1.1.x branch and add related CI jobs

.github/workflows/build-test.yml, .github/workflows/format.yml, .github/workflows/headers.yml, .github/workflows/link-validator.yml, .github/workflows/nightly-snapshot-dependency-test.yml, .github/workflows/pr-labeler.yml, .github/workflows/publish-1.0-docs.yml, .github/workflows/publish-1.0-snapshots.yml, .github/workflows/publish-1.1-docs.yml, .github/workflows/publish-1.1-snapshots.yml, .github/workflows/publish-nightly.yml, .github/workflows/scala-steward.yml
=> pin actions to hashes

project/Common.scala, runtime/src/main/scala/org/apache/pekko/grpc/javadsl/GrpcExceptionHandler.scala, runtime/src/main/scala/org/apache/pekko/grpc/javadsl/GrpcMarshalling.scala
=> add nowarn annotations due to compiler warnings

plugin-tester-java/build.gradle, plugin-tester-java/pom.xml, plugin-tester-scala/build.gradle, plugin-tester-scala/pom.xml
* small step to removing Scala 2.12 support in 2.0.0
=> run maven and gradle tests with scala 2.13

runtime/src/test/scala/org/apache/pekko/grpc/internal/MetadataImplSpec.scala
=> add tests for Java DSL Metadata
